EatOutDir/ViewModels/HomeIndexViewModel.cs
using System;
using System.Collections.Generic;
using OdeToFood.models;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public HomeIndexViewModel()
        {
        }

        public IEnumerable<Restaurant> Restaurants
        {
            get;
            set;
        }

        public string CurrentMessage
        {
            get;
            set;
        }
    }
}

EatOutDir/ViewModels/RestaurantEditModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using OdeToFood.models;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        public RestaurantEditModel()
        {
        }

        [Required,MaxLength(80) ]
        public string Name
        {
            get;
            set;
        }

        public CuisineType Cuisine
        {
            get;
            set;
        }
    }
}

EatOutDir/Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Account
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

EatOutDir/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public void OnGet(string name)
        {
            CurrentGreeting = $"{name}:{_greeter.GetMessageOfTheday()}";
        }
    }
}

EatOutDir/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantdata;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantdata)
        {
            _restaurantdata = restaurantdata;
        }

        public IActionResult OnGet(int id)
        {

          Restaurant =  _restaurantdata.Get(id);

            if(Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                _restaurantdata.Update(Restaurant);
                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }
            return Page();
        }
    }
}

EatOutDir/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeeter)
        {
            _greeter = greeeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheday();
            return View("Default", model);
        }
    }
}

EatOutDir/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

EatOutDir/Pages/Account/SignedOut.cshtml
@page

<h1>You are signed out.</h1>
<a class="btn btn-default" style="margin-right:5px; margin-top:8px" asp-controller="Home" asp-action="Index">Go Home</a>

EatOutDir/Pages/Greeting.cshtml
@page

@model GreetingModel

@*<div>@Model.CurrentGreeting</div>*@

EatOutDir/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants

@model EditModel


<h1>Edit @Model.Restaurant.Name</h1>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />

    <div>
        <h3><b>Welcome!!</b>    @User.Identity.Name</h3>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="Restaurant.Cuisine"></label>
        <select asp-for="Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Restaurant.Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save" />
</form>

EatOutDir/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<style>
.display { position: relative; background: /*linear-gradient(#242222, transparent),*/ url("https://images.unsplash.com/photo-1496389429868-ef51f7140b1e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c917a775b202d8dce8d9e2aa54444903&auto=format&fit=crop&w=1329&q=80"); background-size: cover; background-position: center; background-repeat: no-repeat; background-attachment: initial; }

    .font1 {
        font-family: American, Typewriter, serif;
        font-size: medium;
        align-self: center;
        color:black;
    }

    .panel1 {
        background: linear-gradient(rgba(174, 191, 169, 0.70), transparent)
    }
</style>


<body class="display">
    <nav class="navbar navbar-default navbar-fixed-top" >
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" style="color: black; text-align:center" href="/">EatOut</a>
            </div>
            <div class="navbar-right">
                @*<vc:login-logout></vc:login-logout>*@
                @if (User.Identity.IsAuthenticated)
                {
                    
                    <a asp-controller="Account" asp-action="Logout">LogOut</a>
                }
                else
                {
                    <a class="btn btn-default" style="margin-right:5px; margin-top:8px" asp-controller="Account" asp-action="Login"> LogIn </a>
                }
            </div>
        </div>
    </nav>
   
    
    <div class="container font1 panel1" style="margin-left:34%; margin-top:30% ;width:30%">
        
        @RenderBody()
    </div>
    <div>
        @DateTime.Now.Year
    </div>
    <div>
        @RenderSection("footer", required: false)
    </div>
</body>
</html>

EatOutDir/Views/Home/Create.cshtml
@model Restaurant

@{ 
    ViewBag.Title = "Add a Restaurant";
}

<h1>Create</h1>

<form method="post">

    <div>
        <label asp-for="Name"></label>
    <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
    <select asp-for="Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save" />

</form>

EatOutDir/Views/Home/Details.cshtml
@model Restaurant

@{ 
    ViewBag.Title = Model.Name;
}

<style>
    .panel1 {
        background: linear-gradient(#897730, transparent)
    }

    .btn-default{
        color:black
    }
</style>

<section class="panel-default">
    <h1 class="panel-heading panel1">@Model.Name</h1>
    <div class="panel-body panel1" style="color:white">
        Id: @Model.Id
    </div>
    <div class="panel-footer panel1" style="color:white">
        Cuisine: @Model.Cuisine
    </div>
</section>
<br />
    <br />
<a class="btn btn-default " style="color:black" asp-action="Index" asp-controller="Home">Back to List</a>

EatOutDir/Views/Home/Index.cshtml
@model HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .font {
        font-family: American, Typewriter, serif;
        color: white;
        /*font-size:25%;*/
        text-align: center
    }
</style>
<li>
    <h1 class="font"><b>All Restaurants</b></h1><br />
    
    
</li>
<br />

@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)

}


<a class="btn btn-primary" asp-action="Create">Add Restaurant</a>

<br>

EatOutDir/Views/Home/_Summary.cshtml
@model Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine : @Model.Cuisine
    </div>

    <div class="panel-footer">
       <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a> <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">More</a>
       
    </div>
    <br />
</section>

EatOutDir/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

EatOutDir/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div>Hello, @User.Identity.Name</div>
    <a asp-controller="Account" asp-action="Logout">LogOut</a>
}
else
{
    <a class="btn btn-default" asp-controller = "Account" asp-action="Logout"> LogOut </a>
}

EatOutDir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch:400,700|Sirin+Stencil" rel="stylesheet">


    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<style>

.display { position: relative; background: /*linear-gradient(#242222, transparent),*/ url("https://images.unsplash.com/photo-1521389385985-0fa3ff457f9b?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a80bbdc6b44e7ec0f613a7d7ef683bd1&auto=format&fit=crop&w=1351&q=80"); background-size: cover; background-position: center; background-repeat: no-repeat; background-attachment: initial; }

    .font1 {
        font-family: American, Typewriter, serif;
        font-size:medium;
        align-self: center;
    }

    .panel1{
        background:linear-gradient(#242222, transparent)
    }
</style>
<body class="display" >
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">EatOut</a>
            </div>
            <div class="navbar-right">
                @*<vc:login-logout></vc:login-logout>*@
                @if (User.Identity.IsAuthenticated)
    {
            <div>Hello, @User.Identity.Name</div>
            <a asp-controller="Account" asp-action="Logout">LogOut</a>
}
else
{
            <a class="btn btn-default" style="margin-right:5px; margin-top:8px" asp-controller="Account" asp-action="Login"> LogIn </a>
}
            </div>
        </div>
    </nav>
    <br />
        <br />
            <br />
                <br />
    <div class="container font1 panel1" style="margin-left:34%; margin-top:7% ;width:30%">
        @RenderBody()
        <div>
            @DateTime.Now.Year
        </div>
    </div>

    @*<footer class="container-fluid">
        <br />
        @await Component.InvokeAsync("Greeter")
    </footer>*@

        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
</body>
</html>